-- MySQL Script generated by MySQL Workbench
-- Fri Jul 12 17:21:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema fpdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fpdb` ;

-- -----------------------------------------------------
-- Schema fpdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fpdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `fpdb` ;

-- -----------------------------------------------------
-- Table `fpdb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fpdb`.`products` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fpdb`.`products` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `short_desc` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fpdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fpdb`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fpdb`.`users` (
  `is_active` BIT(1) NULL DEFAULT b'1',
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `role` ENUM('CUSTOMER', 'ADMINAS') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
